#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="icoFoam"

runApplication blockMesh
runApplication decomposePar
mpirun -np 2 $application -parallel > log.$application