#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoOversetFoam"

\cp -f blockMeshDict constant/polyMesh/blockMeshDict
runApplication blockMesh
\cp -f boundary constant/polyMesh/boundary
runApplication setSet -noFunctionObjects -batch setBatch.batch
\rm -f constant/polyMesh/sets/*_old constant/polyMesh/sets/*_old.gz
runApplication setsToZones -noFunctionObjects

runApplication potentialOversetFoam -noFunctionObjects -writep

# Run in serial
#runApplication $application

# Run in parallel
runApplication decomposePar -cellDist
runApplication decomposeSets -writeEmptySets
runParallel $application 2
