#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="overPimpleDyMFoam"

# Create background mesh
runApplication blockMesh -sets

restore0Dir

# Use cellSets to write zoneID
runApplication setFields

# Run potential foam to get some inital fields
runApplication overPotentialFoam -noFunctionObjects -writep

# Run in parallel
runApplication decomposePar -cellDist
mpirun -np 2 -oversubscribe $application -parallel > log.$application
