#!/bin/bash
# Run from this directory
cd "${0%/*}" || exit
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Show some info
#------------------------------------------------------------------------------
clear
source .color
source .infoAndChecks
sleep 2

#------------------------------------------------------------------------------
# Compile cfd2lcs library
#------------------------------------------------------------------------------
echo -en "

${GREEN}1. Compilation of third party library libcfd2lcs${NC}
-------------------------------------------------------------------------------
"
cd LCSFunctionObject/libcfd2lcs
make FOR_OPENFOAM 2> ../../buildlog.libcfd2lcs
cd ../..

#------------------------------------------------------------------------------
# Compile the function object
#------------------------------------------------------------------------------
echo -en "

${GREEN}2. Compilation of the function object${NC}
-------------------------------------------------------------------------------
"
wmake libso LCSFunctionObject | tee buildlog.LCSFunctionObject
