#!/bin/sh

# run from this directory
cd ${0%/*} || exit 1

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase 
rm -r cfd2lcs*
# ----------------------------------------------------------------- end-of-file