#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

compileApplication doubleGyre
runApplication blockMesh
runApplication decomposePar

mpirun -np 2 doubleGyre -parallel > log.doubleGyre
