#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

compileApplication doubleGyre
runApplication blockMesh

runApplication decomposePar -constant
mpirun -np 8 -oversubscribe doubleGyre -parallel > log.doubleGyre