#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

compileApplication doubleGyre
runApplication blockMesh

runApplication decomposePar
mpirun -np 8 doubleGyre -parallel
# runApplication doubleGyre