#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

compileApplication abcFlow
runApplication blockMesh
runApplication decomposePar -constant

mpirun -np 2 -oversubscribe abcFlow -parallel > log.abcFlow
