#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

compileApplication abcFlow
runApplication blockMesh
runApplication decomposePar

mpirun -np 2 abcFlow -parallel > log.abcFlow
