#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="pimpleFoam"

cp -r 0_potential 0
#cp -r 0_org 0
runApplication blockMesh
runApplication renumberMesh -overwrite -noFunctionObjects

runApplication -l log.blockMeshLCS blockMesh -region LCS

runApplication decomposePar
runApplication -l log.decomposeParLCS decomposePar -region LCS

mpirun -np 2 $application -parallel > log.$application