#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="pimpleFoam"

# copy results from the potentialFoam solver
cp -r 0_potential 0
#cp -r 0_org 0

runApplication blockMesh
runApplication renumberMesh -overwrite -noFunctionObjects

runApplication -s LCS blockMesh -region LCS

runApplication decomposePar
runApplication -s LCS decomposePar -region LCS

mpirun -np 2 -oversubscribe $application -parallel > log.$application